---
- name: Run Docker containers
  hosts: jiraserver
  become: yes

  tasks:
    - name: Step 1 - Check if Docker is installed
      command: "docker --version"
      ignore_errors: yes
      register: docker_installed

    - name: Step 2 - Install Docker if not installed
      block:
        - name: Install Docker (Ubuntu)
          apt:
            name: docker.io
            state: present
          when: docker_installed.rc != 0

        - name: Start Docker service
          systemd:
            name: docker
            state: started
            enabled: yes
          when: docker_installed.rc != 0
      when: docker_installed.rc != 0

    - name: Step 3 - Run Docker containers
      command: "docker run --rm -dit --name container{{ item }} --hostname container{{ item }} ubuntu:latest"
      with_sequence: start=1 end=10
